"""
dynamics.py
===========
Right-hand-side (RHS) functions for the four Wilson–Cowan coupling
architectures studied in:

    Hernández et al. (2025) "Higher-order statistical structure emerges from
    nonlinear dynamics without explicit higher-order coupling."

Each function returns dstate/dt = [dE/dt, dI/dt] for the full network
given the current state vector, and is designed to be passed directly to
a numerical integrator (e.g., ``rk4_step`` in simulation.py).

Coupling architectures implemented
-----------------------------------
1. ``wc_rhs``                        — Pairwise additive (PA)
2. ``wc_rhs_additive``               — Pairwise diffusive (PD)
3. ``wc_rhs_higher_order``           — Third-order additive (TA)
4. ``wc_rhs_higher_order_additive``  — Third-order diffusive (TD)

Variants with a free sigmoid-slope parameter (A instead of node-level aE)
are provided for the a_E–K parameter sweeps:
    ``wc_rhs_a``, ``wc_rhs_higher_order_a``

A numerical Jacobian utility is also included for stability analysis.

State vector convention
-----------------------
state = [E_0, E_1, ..., E_{N-1}, I_0, I_1, ..., I_{N-1}]   (length 2N)
"""

import numpy as np
from .parameters import param_nodes


# ---------------------------------------------------------------------------
# Sigmoid (logistic) transfer function
# ---------------------------------------------------------------------------

def S(x: float, a: float, theta: float) -> float:
    """Logistic sigmoid transfer function.

    Defined as S(x; a) = 1 / (1 + exp(-a * x)).  The threshold parameter
    *theta* is accepted for API compatibility but is currently unused (the
    threshold is absorbed into the local connectivity terms).

    Parameters
    ----------
    x : float or np.ndarray
        Input to the transfer function.
    a : float
        Sigmoid slope (steepness parameter a_E or a_I).
    theta : float
        Sigmoid threshold (currently not applied; kept for interface
        consistency with earlier versions of the code).

    Returns
    -------
    float or np.ndarray
        Output of the sigmoid, in the interval (0, 1).
    """
    return 1.0 / (1.0 + np.exp(-a * x))


# ---------------------------------------------------------------------------
# Pairwise additive coupling  [Eq. (1) in the manuscript]
# ---------------------------------------------------------------------------

def wc_rhs(state: np.ndarray, P, K: float, M: np.ndarray) -> np.ndarray:
    """RHS of the Wilson–Cowan ODE with *pairwise additive* coupling.

    The excitatory coupling term is:
        C_i = K * sum_j M_ij * E_j

    Any higher-order statistical structure generated by this model must arise
    solely from the nonlinear sigmoid, not from explicit higher-order terms.

    Parameters
    ----------
    state : np.ndarray, shape (2N,)
        Concatenated state vector [E_0,...,E_{N-1}, I_0,...,I_{N-1}].
    P : float or np.ndarray, shape (N,)
        External drive.  Scalar applies the same drive to every node.
    K : float
        Global pairwise coupling strength.
    M : np.ndarray, shape (N, N)
        Binary (or weighted) structural connectivity matrix.

    Returns
    -------
    np.ndarray, shape (2N,)
        Time derivatives [dE/dt, dI/dt].
    """
    N = M.shape[0]
    E = state[:N]
    I = state[N:]

    # Compute coupling input for all nodes at once: K * M @ E
    coupling = K * (M @ E)

    dE_dt = np.zeros(N)
    dI_dt = np.zeros(N)

    for i in range(N):
        p = param_nodes[i]
        P_i = P if np.isscalar(P) else P[i]

        # Excitatory population: local recurrent + inhibition + drive + coupling
        dE_dt[i] = (
            -E[i]
            + S(
                p["cEE"] * E[i] - p["cEI"] * I[i] + P_i + coupling[i],
                p["aE"],
                p["thetaE"],
            )
        ) / p["tauE"]

        # Inhibitory population: local excitation + inhibitory self-connection
        dI_dt[i] = (
            -I[i]
            + S(
                p["cIE"] * E[i] - p["cII"] * I[i] + p["Q"],
                p["aI"],
                p["thetaI"],
            )
        ) / p["tauI"]

    return np.concatenate([dE_dt, dI_dt])


# ---------------------------------------------------------------------------
# Pairwise diffusive coupling  [Eq. (2) in the manuscript]
# ---------------------------------------------------------------------------

def wc_rhs_additive(state: np.ndarray, P, K: float, M: np.ndarray) -> np.ndarray:
    """RHS of the Wilson–Cowan ODE with *pairwise diffusive* coupling.

    The diffusive coupling term is:
        C_i = K * sum_j M_ij * (E_j - E_i) = K * [(M @ E)_i - d_i * E_i]

    where d_i = sum_j M_ij is the degree of node i.  This coupling depends
    only on *differences* between excitatory states, so it vanishes for
    homogeneous configurations and suppresses common-mode activity.

    Parameters
    ----------
    state : np.ndarray, shape (2N,)
    P : float or np.ndarray, shape (N,)
    K : float
    M : np.ndarray, shape (N, N)

    Returns
    -------
    np.ndarray, shape (2N,)
    """
    N = M.shape[0]
    E = state[:N]
    I = state[N:]

    # Node degrees (sum of each row of M)
    degree = M.sum(axis=1)

    # Diffusive coupling: K * (M @ E - degree * E)
    coupling = K * (M @ E - degree * E)

    dE_dt = np.zeros(N)
    dI_dt = np.zeros(N)

    for i in range(N):
        p = param_nodes[i]
        P_i = P if np.isscalar(P) else P[i]

        dE_dt[i] = (
            -E[i]
            + S(
                p["cEE"] * E[i] - p["cEI"] * I[i] + P_i + coupling[i],
                p["aE"],
                p["thetaE"],
            )
        ) / p["tauE"]

        dI_dt[i] = (
            -I[i]
            + S(
                p["cIE"] * E[i] - p["cII"] * I[i] + p["Q"],
                p["aI"],
                p["thetaI"],
            )
        ) / p["tauI"]

    return np.concatenate([dE_dt, dI_dt])


# ---------------------------------------------------------------------------
# Third-order additive coupling  [Eq. (3) in the manuscript]
# ---------------------------------------------------------------------------

def wc_rhs_higher_order(state: np.ndarray, P, K3: float,
                         T_ho: np.ndarray) -> np.ndarray:
    """RHS of the Wilson–Cowan ODE with *third-order additive* coupling.

    The explicit higher-order coupling term is:
        C_i = K3 * sum_{j,k} T_ho[i,j,k] * E_j * E_k

    The interaction is already quadratic in the excitatory states *before*
    passing through the sigmoid, making this the explicit HOI benchmark.

    Parameters
    ----------
    state : np.ndarray, shape (2N,)
    P : float or np.ndarray, shape (N,)
    K3 : float
        Higher-order coupling strength.
    T_ho : np.ndarray, shape (N, N, N)
        Third-order interaction tensor.

    Returns
    -------
    np.ndarray, shape (2N,)
    """
    N = T_ho.shape[0]
    E = state[:N]
    I = state[N:]

    dE_dt = np.zeros(N)
    dI_dt = np.zeros(N)

    for i in range(N):
        p = param_nodes[i]
        P_i = P if np.isscalar(P) else P[i]

        # Compute the bilinear higher-order input: sum_{j,k} T[i,j,k] E_j E_k
        higher_order_input = 0.0
        for j in range(N):
            for k in range(N):
                higher_order_input += T_ho[i, j, k] * E[j] * E[k]

        dE_dt[i] = (
            -E[i]
            + S(
                p["cEE"] * E[i] - p["cEI"] * I[i] + P_i + K3 * higher_order_input,
                p["aE"],
                p["thetaE"],
            )
        ) / p["tauE"]

        dI_dt[i] = (
            -I[i]
            + S(
                p["cIE"] * E[i] - p["cII"] * I[i] + p["Q"],
                p["aI"],
                p["thetaI"],
            )
        ) / p["tauI"]

    return np.concatenate([dE_dt, dI_dt])


# ---------------------------------------------------------------------------
# Third-order diffusive coupling  [Eq. (4) in the manuscript]
# ---------------------------------------------------------------------------

def wc_rhs_higher_order_additive(state: np.ndarray, P, K3: float,
                                   T_ho: np.ndarray) -> np.ndarray:
    """RHS of the Wilson–Cowan ODE with *third-order diffusive* coupling.

    The diffusive higher-order coupling term is:
        C_i = K3 * (δ^(i))^T T_i δ^(i)

    where δ^(i) = E - E_i * 1 is the vector of deviations from node i's
    state.  This is equivalent to:
        C_i = K3 * sum_{j,k} T_ho[i,j,k] * (E_j - E_i) * (E_k - E_i)

    The diffusive form vanishes for homogeneous states and selectively
    amplifies deviations from synchrony.

    Parameters
    ----------
    state : np.ndarray, shape (2N,)
    P : float or np.ndarray, shape (N,)
    K3 : float
    T_ho : np.ndarray, shape (N, N, N)

    Returns
    -------
    np.ndarray, shape (2N,)
    """
    N = T_ho.shape[0]
    E = state[:N]
    I = state[N:]

    dE_dt = np.zeros(N)
    dI_dt = np.zeros(N)

    for i in range(N):
        p = param_nodes[i]
        P_i = P if np.isscalar(P) else P[i]

        # Deviation vector: δ^(i) = E - E_i (differences from node i's state)
        Ti = T_ho[i]          # N×N slice of the tensor for node i
        diff = E - E[i]       # shape (N,)

        # Quadratic form: δ^T T_i δ
        higher_order_input = diff @ Ti @ diff

        dE_dt[i] = (
            -E[i]
            + S(
                p["cEE"] * E[i] - p["cEI"] * I[i] + P_i + K3 * higher_order_input,
                p["aE"],
                p["thetaE"],
            )
        ) / p["tauE"]

        dI_dt[i] = (
            -I[i]
            + S(
                p["cIE"] * E[i] - p["cII"] * I[i] + p["Q"],
                p["aI"],
                p["thetaI"],
            )
        ) / p["tauI"]

    return np.concatenate([dE_dt, dI_dt])


# ---------------------------------------------------------------------------
# Sigmoid-slope sweep variants (a_E as a free parameter, P fixed)
# ---------------------------------------------------------------------------
# The following two functions replace the per-node aE by a global sweep
# parameter A, while fixing P = 7 (the oscillatory regime identified in
# the P–K phase diagrams).  They are used to generate Figs. 3 and related
# a_E–K contour maps.

def wc_rhs_a(state: np.ndarray, A, K: float, M: np.ndarray,
              P: float = 7) -> np.ndarray:
    """Pairwise additive RHS with a free global sigmoid slope A.

    Identical to ``wc_rhs`` but overrides the per-node aE with the scalar
    (or per-node array) *A*.  External drive P is fixed (default P = 7).

    Parameters
    ----------
    state : np.ndarray, shape (2N,)
    A : float or np.ndarray, shape (N,)
        Sigmoid slope to apply to the excitatory population.
    K : float
        Pairwise coupling strength.
    M : np.ndarray, shape (N, N)
    P : float, optional
        Fixed external drive (default 7).

    Returns
    -------
    np.ndarray, shape (2N,)
    """
    N = M.shape[0]
    E = state[:N]
    I = state[N:]

    coupling = K * (M @ E)

    dE_dt = np.zeros(N)
    dI_dt = np.zeros(N)

    for i in range(N):
        p = param_nodes[i]
        A_i = A if np.isscalar(A) else A[i]

        dE_dt[i] = (
            -E[i]
            + S(
                p["cEE"] * E[i] - p["cEI"] * I[i] + P + coupling[i],
                A_i,          # override sigmoid slope with sweep value
                p["thetaE"],
            )
        ) / p["tauE"]

        dI_dt[i] = (
            -I[i]
            + S(
                p["cIE"] * E[i] - p["cII"] * I[i] + p["Q"],
                p["aI"],
                p["thetaI"],
            )
        ) / p["tauI"]

    return np.concatenate([dE_dt, dI_dt])


def wc_rhs_higher_order_a(state: np.ndarray, A, K3: float,
                            T_ho: np.ndarray, P: float = 7) -> np.ndarray:
    """Third-order additive RHS with a free global sigmoid slope A.

    Identical to ``wc_rhs_higher_order`` but overrides the per-node aE
    with the scalar *A*.  External drive P is fixed (default P = 7).

    Parameters
    ----------
    state : np.ndarray, shape (2N,)
    A : float or np.ndarray, shape (N,)
        Sigmoid slope for the excitatory population.
    K3 : float
        Higher-order coupling strength.
    T_ho : np.ndarray, shape (N, N, N)
    P : float, optional
        Fixed external drive (default 7).

    Returns
    -------
    np.ndarray, shape (2N,)
    """
    N = T_ho.shape[0]
    E = state[:N]
    I = state[N:]

    dE_dt = np.zeros(N)
    dI_dt = np.zeros(N)

    for i in range(N):
        p = param_nodes[i]
        A_i = A if np.isscalar(A) else A[i]

        # Bilinear higher-order input
        higher_order_input = 0.0
        for j in range(N):
            for k in range(N):
                higher_order_input += T_ho[i, j, k] * E[j] * E[k]

        dE_dt[i] = (
            -E[i]
            + S(
                p["cEE"] * E[i] - p["cEI"] * I[i] + P + K3 * higher_order_input,
                A_i,
                p["thetaE"],
            )
        ) / p["tauE"]

        dI_dt[i] = (
            -I[i]
            + S(
                p["cIE"] * E[i] - p["cII"] * I[i] + p["Q"],
                p["aI"],
                p["thetaI"],
            )
        ) / p["tauI"]

    return np.concatenate([dE_dt, dI_dt])


# ---------------------------------------------------------------------------
# Numerical Jacobian  (for stability / bifurcation analysis)
# ---------------------------------------------------------------------------

def numerical_jacobian(f, x0: np.ndarray, eps: float = 1e-6) -> np.ndarray:
    """Compute the Jacobian of *f* at *x0* using forward finite differences.

    Parameters
    ----------
    f : callable
        Function mapping an (n,) array to an (n,) array.
    x0 : np.ndarray, shape (n,)
        Point at which to evaluate the Jacobian.
    eps : float, optional
        Finite-difference step size (default 1e-6).

    Returns
    -------
    J : np.ndarray, shape (n, n)
        Jacobian matrix ∂f_i/∂x_j evaluated at x0.
    """
    n = len(x0)
    J = np.zeros((n, n))
    f0 = f(x0)

    for i in range(n):
        x_eps = x0.copy()
        x_eps[i] += eps
        # Forward difference: (f(x + ε e_i) - f(x)) / ε
        J[:, i] = (f(x_eps) - f0) / eps

    return J
